name: SpeedMeter
options:
  bundleIdPrefix: com.sayandwips.speedmeter
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: U9VKCZGR2B

targets:
  SpeedMeter:
    type: application
    platform: iOS
    sources:
      - path: SpeedMeter
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sayandwips.speedmeter
        INFOPLIST_FILE: SpeedMeter/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_ENTITLEMENTS: SpeedMeter/SpeedMeter.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_PREVIEWS: YES
    dependencies:
      - target: SpeedMeterWidgetExtension
        embed: true

  SpeedMeterWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: SpeedMeterWidget
        excludes:
          - "**/.DS_Store"
      - path: SpeedMeter/Models/SpeedData.swift
      - path: SpeedMeter/Views/SpeedMeterLiveActivity.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sayandwips.speedmeter.widget
        INFOPLIST_FILE: SpeedMeterWidget/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_ENTITLEMENTS: SpeedMeterWidget/SpeedMeterWidget.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES
